version: '3.8'

services:
  # Main Quizzler Backend Service
  backend:
    image: adityatorgal17/quizzler-backend:latest
    container_name: quizzler_backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # For direct access during development/testing
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Persistent data storage
    networks:
      - quizzler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/realtime/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    networks:
      - quizzler-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Let's Encrypt SSL Certificates
  certbot:
    image: certbot/certbot:latest
    container_name: quizzler_certbot
    restart: "no"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email adityatorgal581@gmail.com --agree-tos --no-eff-email --force-renewal -d quizzler-backend.adityatorgal.me

networks:
  quizzler-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
